
package com.cjl6;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-30T08:10:52.574+08:00
 * Generated source version: 3.3.1
 *
 */

public class MyServicePortType_MyServiceImplPort_Server{

    protected MyServicePortType_MyServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MyServiceImplPortImpl();
        String address = "http://localhost:8080/myservice";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new MyServicePortType_MyServiceImplPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
