package com.cjl6;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-29T07:33:56.589+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://cjl.com/", name = "MyServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MyServicePortType {

    @WebMethod
    @RequestWrapper(localName = "getPersonById", targetNamespace = "http://cjl.com/", className = "com.cjl.IdType")
    @ResponseWrapper(localName = "getPersonByIdResponse", targetNamespace = "http://cjl.com/", className = "com.cjl.PersonType")
    public void getPersonById(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(mode = WebParam.Mode.OUT, name = "name", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> name,
        @WebParam(mode = WebParam.Mode.OUT, name = "address", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> address,
        @WebParam(mode = WebParam.Mode.OUT, name = "date", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> date
    );
}
