
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cjl6;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-29T07:33:56.535+08:00
 * Generated source version: 3.3.1
 *
 */

@javax.jws.WebService(
                      serviceName = "MyServiceImplService",
                      portName = "MyServiceImplPort",
                      targetNamespace = "http://cjl.com/",
                      wsdlLocation = "file:src/com/cjl6/myservice.wsdl",
                      endpointInterface = "com.cjl.MyServicePortType")

public class MyServiceImplPortImpl implements MyServicePortType {

    private static final Logger LOG = Logger.getLogger(MyServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cjl.MyServicePortType#getPersonById(int id, java.lang.String name, java.lang.String address, javax.xml.datatype.XMLGregorianCalendar date)*
     */
    public void getPersonById(int id, javax.xml.ws.Holder<java.lang.String> name, javax.xml.ws.Holder<java.lang.String> address, javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> date) {
        LOG.info("Executing operation getPersonById");
        System.out.println(id);
        try {
            java.lang.String nameValue = "";
            name.value = nameValue;
            java.lang.String addressValue = "";
            address.value = addressValue;
            javax.xml.datatype.XMLGregorianCalendar dateValue = null;
            date.value = dateValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
