
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cjl8;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-06-03T22:29:15.733+08:00
 * Generated source version: 3.3.1
 *
 */

@WebService(
                      serviceName = "MyServiceImplService",
                      portName = "MyServiceImplPort",
                      targetNamespace = "http://cjl.com/",
                      wsdlLocation = "file:src/com/cjl6/myservice.wsdl",
                      endpointInterface = "com.cjl8.MyServicePortType")

public class MyServiceImplPortImpl implements MyServicePortType {

    private static final Logger LOG = Logger.getLogger(MyServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cjl.MyServicePortType#getPersonById(com.cjl.IdType parameters)*
     */
    public com.cjl8.PersonType getPersonById(IdType parameters) {
        LOG.info("Executing operation getPersonById");
        System.out.println(parameters);
        try {
            com.cjl8.PersonType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
