
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cjl8;

import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-06-04T21:41:51.481+08:00
 * Generated source version: 3.3.1
 *
 */

@WebService(
                      serviceName = "MyServiceImplService",
                      portName = "MyServiceImplPort",
                      targetNamespace = "http://cjl.com/",
                      wsdlLocation = "file:src/com/cjl8/myservice.wsdl",
                      endpointInterface = "com.cjl8.MyServicePortType")

public class MyServiceImplPortImpl implements MyServicePortType {

    private static final Logger LOG = Logger.getLogger(MyServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cjl.MyServicePortType#getPersonById(com.cjl.AttachmentType parameters)*
     */
    public void getPersonById(AttachmentType parameters) {
        LOG.info("Executing operation getPersonById");
        System.out.println(parameters);

//        文件上传
        try {

            byte[] buffer = parameters.getContent();

            OutputStream os = new FileOutputStream("temp_out.txt");
            os.write(buffer);
            os.close();
        }catch (Exception e){
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }

}
