
package com.cjl5;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.cjl.MyService;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-05-24T08:19:21.182+08:00
 * Generated source version: 3.3.1
 *
 */
public final class MyService_MyServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cjl.com/", "MyServiceImplService");

    private MyService_MyServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MyServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MyServiceImplService ss = new MyServiceImplService(wsdlURL, SERVICE_NAME);
        MyService port = ss.getMyServiceImplPort();

        {
        System.out.println("Invoking hello2...");
        String _hello2_arg0 = "";
        String _hello2_arg1 = "";
        String _hello2__return = port.hello2(_hello2_arg0, _hello2_arg1);
        System.out.println("hello2.result=" + _hello2__return);


        }
        {
        System.out.println("Invoking hello...");
        String _hello_name = "";
        String _hello__return = port.hello(_hello_name);
        System.out.println("hello.result=" + _hello__return);


        }

        System.exit(0);
    }

}
